typography_spectrum: 0.5790604008361697
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fee42d'
    - '#cdcdcd'
    - '#888888'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.5228741860482842
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.93738
analytics:
  google: null
  facebook: null
  twitter: null
name: Expect to Receive and Surprise Yourself
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: EXPECT to RECEIVE
purpose: []
