name: WeAreNotGod
favicon: null
layout_spectrum: 0.93738
typography_spectrum: 0.5790604008361697
title: We Are Not God
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fee42d'
    - '#cdcdcd'
    - '#888888'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5228741860482842
purpose: []
